"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 03:01:01.477389
"""

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_alert_id'), ['alert_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_ticker'), ['ticker'], unique=False)

    op.create_table('analyst_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('analyst_key', sa.String(length=200), nullable=True),
    sa.Column('analyst_name', sa.String(length=200), nullable=True),
    sa.Column('firm', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=True),
    sa.Column('rating', sa.String(length=60), nullable=True),
    sa.Column('rating_prior', sa.String(length=60), nullable=True),
    sa.Column('rating_norm', sa.Integer(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('target_prior', sa.Float(), nullable=True),
    sa.Column('price_when_posted', sa.Float(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('source_uid', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_uid')
    )
    with op.batch_alter_table('analyst_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_actions_analyst_key'), ['analyst_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_actions_firm'), ['firm'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_actions_ticker'), ['ticker'], unique=False)

    op.create_table('analyst_scores',
    sa.Column('analyst_key', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('n_calls', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('excess_3m', sa.Float(), nullable=True),
    sa.Column('excess_6m', sa.Float(), nullable=True),
    sa.Column('excess_12m', sa.Float(), nullable=True),
    sa.Column('bullish_bias', sa.Float(), nullable=True),
    sa.Column('herding', sa.Float(), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('config_hash', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('analyst_key', 'scope')
    )
    op.create_table('app_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('share_token', sa.String(length=24), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=True),
    sa.Column('p50', sa.Float(), nullable=True),
    sa.Column('p90', sa.Float(), nullable=True),
    sa.Column('prob_up', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trust_rating', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('size_bucket', sa.String(length=10), nullable=True),
    sa.Column('vol_bucket', sa.String(length=10), nullable=True),
    sa.Column('pillars_json', sa.JSON(), nullable=True),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('config_hash', sa.String(length=16), nullable=False),
    sa.Column('is_backtest', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    with op.batch_alter_table('app_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_snapshots_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_snap_ticker_asof', ['ticker', 'as_of', 'is_backtest'], unique=False)

    op.create_table('companies',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('exchange', sa.String(length=40), nullable=True),
    sa.Column('sic', sa.Integer(), nullable=True),
    sa.Column('sic_desc', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_cik'), ['cik'], unique=False)

    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', 'kind', name='uq_action')
    )
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_actions_ticker'), ['ticker'], unique=False)

    op.create_table('estimate_revisions',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=20), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'period_end', 'metric', 'as_of')
    )
    op.create_table('estimates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('metric', sa.String(length=20), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estimates_ticker'), ['ticker'], unique=False)

    op.create_table('filings',
    sa.Column('accn', sa.String(length=30), nullable=False),
    sa.Column('cik', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('items', sa.String(length=200), nullable=True),
    sa.Column('primary_doc', sa.String(length=300), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('accn')
    )
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filings_cik'), ['cik'], unique=False)

    op.create_table('firm_scores',
    sa.Column('firm', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('n_calls', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('excess_3m', sa.Float(), nullable=True),
    sa.Column('excess_6m', sa.Float(), nullable=True),
    sa.Column('excess_12m', sa.Float(), nullable=True),
    sa.Column('bullish_bias', sa.Float(), nullable=True),
    sa.Column('herding', sa.Float(), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('config_hash', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('firm', 'scope')
    )
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.Integer(), nullable=False),
    sa.Column('taxonomy', sa.String(length=20), nullable=False),
    sa.Column('concept', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=True),
    sa.Column('fp', sa.String(length=4), nullable=True),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('accn', sa.String(length=30), nullable=True),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('frame', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.create_index('ix_fund_pit', ['cik', 'concept', 'period_end', 'filed_at'], unique=False)

    op.create_table('insider_tx',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('filer', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('tx_date', sa.Date(), nullable=False),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('open_market', sa.Boolean(), nullable=False),
    sa.Column('plan_10b5_1', sa.Boolean(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('owned_after', sa.Float(), nullable=True),
    sa.Column('accn', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insider_tx', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insider_tx_ticker'), ['ticker'], unique=False)

    op.create_table('institutional_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('holder', sa.String(length=300), nullable=False),
    sa.Column('holder_cik', sa.String(length=20), nullable=True),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('filed_at', sa.Date(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('change_shares', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutional_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutional_holdings_ticker'), ['ticker'], unique=False)

    op.create_table('llm_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('llm_cost_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('validator_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_cost_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_cost_log_ticker'), ['ticker'], unique=False)

    op.create_table('macro',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('series_id', 'date')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('cluster_id', sa.String(length=40), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'url', name='uq_news_url')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_ticker'), ['ticker'], unique=False)

    op.create_table('news_analysis',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('materiality', sa.String(length=10), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('prices',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('provider_cache',
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('dataset', sa.String(length=60), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('short_interest',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('short_interest', sa.Float(), nullable=False),
    sa.Column('avg_volume', sa.Float(), nullable=True),
    sa.Column('days_to_cover', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'settlement_date')
    )
    op.create_table('snapshot_outcomes',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('horizon_date', sa.Date(), nullable=False),
    sa.Column('realized_price', sa.Float(), nullable=False),
    sa.Column('realized_return', sa.Float(), nullable=False),
    sa.Column('in_band', sa.Boolean(), nullable=False),
    sa.Column('abs_pct_err', sa.Float(), nullable=False),
    sa.Column('realized_up', sa.Boolean(), nullable=False),
    sa.Column('brier', sa.Float(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('watchlist',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('snapshot_outcomes')
    op.drop_table('short_interest')
    op.drop_table('provider_cache')
    op.drop_table('prices')
    op.drop_table('news_analysis')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_ticker'))

    op.drop_table('news')
    op.drop_table('macro')
    with op.batch_alter_table('llm_cost_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_cost_log_ticker'))

    op.drop_table('llm_cost_log')
    op.drop_table('llm_cache')
    with op.batch_alter_table('institutional_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutional_holdings_ticker'))

    op.drop_table('institutional_holdings')
    with op.batch_alter_table('insider_tx', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insider_tx_ticker'))

    op.drop_table('insider_tx')
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.drop_index('ix_fund_pit')

    op.drop_table('fundamentals')
    op.drop_table('firm_scores')
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filings_cik'))

    op.drop_table('filings')
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estimates_ticker'))

    op.drop_table('estimates')
    op.drop_table('estimate_revisions')
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_actions_ticker'))

    op.drop_table('corporate_actions')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_cik'))

    op.drop_table('companies')
    with op.batch_alter_table('app_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snap_ticker_asof')
        batch_op.drop_index(batch_op.f('ix_app_snapshots_ticker'))

    op.drop_table('app_snapshots')
    op.drop_table('analyst_scores')
    with op.batch_alter_table('analyst_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_actions_ticker'))
        batch_op.drop_index(batch_op.f('ix_analyst_actions_firm'))
        batch_op.drop_index(batch_op.f('ix_analyst_actions_analyst_key'))

    op.drop_table('analyst_actions')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_ticker'))

    op.drop_table('alerts')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_alert_id'))

    op.drop_table('alert_events')
    # ### end Alembic commands ###
